### ISSUE TITLE
launch of daemon container failed

### ISSUE THREAD

**Issue by nicks** [datawire/telepresence-docker-extension-issues#14]
When I try to connect to a cluster, I get this error:

```
launch of daemon container failed: docker: Error response from daemon: Invalid container name (tp-nick.santos@docker.com@nassau.us-east-1.eksctl.io), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed. See 'docker run --help'.
```

Looks like it's trying to generate a container name based on the cluster context, but that won't work because they have different allowed characters?

**Comment by knlambert** [comment]
Hello,

We start a container for each context you try to connect to. I assume the @ is the character causing issues.

Does it work if you rename your context from `tp-nick.santos@docker.com@nassau.us-east-1.eksctl.io` to `tp-nick.santos@docker.com-at-nassau.us-east-1.eksctl.io` ?

**Comment by thallgren** [comment]
We'll have to mangle the name so that it doesn't contain illegal characters. I'll create a PR for that in the telepresence repo.

**Comment by thallgren** [comment]
We have a fix pending for this that will be included in our next release. Meanwhile, the workaround is to use a context name that is a valid docker container name.
