### ISSUE TITLE
How to connect Telepresence Cloud with helm postgres postgis geospatial extension? 

### ISSUE THREAD

**Issue by luismendes070** [datawire/telepresence-docker-extension-issues#2]
Telepresence Logs
StatefulSet my-postgresql.default has multiple interceptable services with port 5432. Please specify the service you want to intercept by passing the --service=<svc> flag.
StatefulSet my-postgresql.default has multiple interceptable services with port 5432. Please specify the service you want to intercept by passing the --service=<svc> flag.
StatefulSet my-postgresql.default has multiple interceptable services with port 5432. Please specify the service you want to intercept by passing the --service=<svc> flag.

**Comment by njayp** [comment]
This is a feature we are working on. I'll let you know as soon as it ships.

**Comment by njayp** [comment]
fixed in v1.0.0
