### ISSUE TITLE
Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by chongkai** [datawire/telepresence-docker-extension-issues#3]
when clicking "Intercept" on one of my services, just saw this error
<img width="393" alt="image" src="https://user-images.githubusercontent.com/5928662/180627139-f6801e50-1b2b-42e7-b3cd-73905e464fbf.png">

Another issue is when I intercept on a deployment, which is exposed on two services, only the ports of one of the services are listed in the Service Port dropdown.

**Comment by njayp** [comment]
Thanks for posting this. I will look into it

**Comment by njayp** [comment]
this should happen less now
