### ISSUE TITLE
Extension failed to intercept

### ISSUE THREAD

**Issue by benja-M-1** [datawire/telepresence-docker-extension-issues#6]
Hi 👋

When testing a new build of Docker Desktop with the Telepresence extension. I used "Get started" sample. 

At the stage "Create Intercept" it raised an error: `Unexpected token A in JSON at position 0`. So I tried again an now I have two errors. I attached screenshots for both tries with the dev tools of the extension. You can see an error in there `Error in configuration: context was not found for specified context: kind-telepresence-demo-cluster` on the command `kubectl get pod --context kind-telepresence-demo-cluster`

* try #1
<img width="1616" alt="Screenshot 2022-08-31 at 17 15 09" src="https://user-images.githubusercontent.com/212269/187715127-a3c85014-fcb6-481a-8754-f0adb0f528cd.png">

* try #2
<img width="1498" alt="Screenshot 2022-08-31 at 17 18 55" src="https://user-images.githubusercontent.com/212269/187715590-5af448fa-8a35-4a5d-8524-d1ed889a3a91.png">

**Comment by benja-M-1** [comment]
This issue is a dupe of #3 actually, closing

**Comment by njayp** [comment]
thanks for putting the time into it, ill let you know how it goes
