### ISSUE TITLE
Unexpected token A in JSON at position 0

### ISSUE THREAD

**Issue by Jaff** [datawire/telepresence-docker-extension-issues#7]
When running the Emojivote demo, this alert appeared after clicking to create intercept. An additional message `workload "voting.default" not found` was present.

**Comment by njayp** [comment]
sorry for the late response. occasionally kind flakes like the "not found" error, we are expanding cluster options for a future release

**Comment by njayp** [comment]
Unexpected token A in JSON at position 0 should happen less
